export { default as Home } from './Home'
export { default as Platform } from './Platform'
export { default as About } from './About'
export { default as Track } from './Track'
export { default as Directory } from './Directory'
export { default as Contact } from './Contact'
